//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_SeeingVR_default p_SeeingVR_default;
        
        public static SteamVR_Input_ActionSet_SeeingVR_default SeeingVR_default
        {
            get
            {
                return SteamVR_Actions.p_SeeingVR_default.GetCopy<SteamVR_Input_ActionSet_SeeingVR_default>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_SeeingVR_default = ((SteamVR_Input_ActionSet_SeeingVR_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_SeeingVR_default>("/actions/SeeingVR_default")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.SeeingVR_default};
        }
    }
}
