//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_SeeingVR_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean RecognizeCurrentImage
        {
            get
            {
                return SteamVR_Actions.seeingVR_default_RecognizeCurrentImage;
            }
        }
        
        public virtual SteamVR_Action_Boolean MakeLaserThicker
        {
            get
            {
                return SteamVR_Actions.seeingVR_default_MakeLaserThicker;
            }
        }
        
        public virtual SteamVR_Action_Boolean StartListening
        {
            get
            {
                return SteamVR_Actions.seeingVR_default_StartListening;
            }
        }
    }
}
